### ISSUE TITLE
Interactive login not working

### ISSUE THREAD

**Issue by ghost** [obreitwi/asfa#7]
When I set `interactive: true` and `use_agent: false`, it prompts me for a password even though my default SSH private key allows me to login to the host normally using the `ssh` binary without a password, but not with asfa for some reason. Instead, it asks me for my password, but even if I enter the password, it always thinks it's wrong.

**Comment by obreitwi** [comment]
Right now, `interactive: true` implies that the private key is password protected. I will add a check to prevent the password prompt even when `interactive: true` is set.

→ Setting `interactive: false` should disable the password prompt and solve your problem in the meantime.

**Comment by ghost** [comment]
I see, in that case I think my problem might be because I use two-factor auth, that interactive mode is still needed to enter the 2FA code even if a password is not required to be entered in any way.

**Comment by ghost** [comment]
With `interactive: false` and `use_agent: false` currently I get this:
```
$ asfa push test.png
$ RUST_BACKTRACE=full asfa push test.png
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -39, msg: "no auth sock variable" }', /home/bp/.cargo/registry/src/github.com-1ecc6299db9ec823/asfa-0.5.2/src/ssh.rs:91:25
stack backtrace:
   0:     0x55e5dac2bd60 - std::backtrace_rs::backtrace::libunwind::trace::ha31cb35ba35052ca
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55e5dac2bd60 - std::backtrace_rs::backtrace::trace_unsynchronized::h914154c46fedb791
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55e5dac2bd60 - std::sys_common::backtrace::_print_fmt::h4bed7544cf4783cc
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:79
   3:     0x55e5dac2bd60 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h71baf994de642464
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:58
   4:     0x55e5dac4e5ac - core::fmt::write::hcb5569f97eae5185
                               at /build/rust/src/rustc-1.47.0-src/library/core/src/fmt/mod.rs:1082
   5:     0x55e5dac271f7 - std::io::Write::write_fmt::hec04380539c975a7
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/io/mod.rs:1514
   6:     0x55e5dac2e090 - std::sys_common::backtrace::_print::h7217f428d769d34f
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:61
   7:     0x55e5dac2e090 - std::sys_common::backtrace::print::heb9b7db110cef504
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:48
   8:     0x55e5dac2e090 - std::panicking::default_hook::{{closure}}::hc8bd48d88d5fcceb
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:200
   9:     0x55e5dac2dddc - std::panicking::default_hook::h4a7994bce6af5114
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:219
  10:     0x55e5dac2e6f3 - std::panicking::rust_panic_with_hook::h796dceade986353b
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:569
  11:     0x55e5dac2e2c9 - std::panicking::begin_panic_handler::{{closure}}::h04c1f5fa60189361
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:476
  12:     0x55e5dac2c1cc - std::sys_common::backtrace::__rust_end_short_backtrace::h1aa5b888ed842ec3
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/sys_common/backtrace.rs:153
  13:     0x55e5dac2e289 - rust_begin_unwind
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:475
  14:     0x55e5dac4c191 - core::panicking::panic_fmt::ha5b47339211aa855
                               at /build/rust/src/rustc-1.47.0-src/library/core/src/panicking.rs:85
  15:     0x55e5dac4bfb3 - core::option::expect_none_failed::hd1c472dae0b64b95
                               at /build/rust/src/rustc-1.47.0-src/library/core/src/option.rs:1221
  16:     0x55e5daa9bc2d - asfa::ssh::SshSession::create::h34bce4782bb75d83
  17:     0x55e5daaa4650 - asfa::main::h4fcd8f9188b5b583
  18:     0x55e5daa6e523 - std::sys_common::backtrace::__rust_begin_short_backtrace::h7c5edc664990ce94
  19:     0x55e5daaa11cd - std::rt::lang_start::{{closure}}::h05c6038f47a10623
  20:     0x55e5dac2eade - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h3b46348dde94a3ab
                               at /build/rust/src/rustc-1.47.0-src/library/core/src/ops/function.rs:259
  21:     0x55e5dac2eade - std::panicking::try::do_call::h65a06556d74549bf
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:373
  22:     0x55e5dac2eade - std::panicking::try::h906dbc9901f62921
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panicking.rs:337
  23:     0x55e5dac2eade - std::panic::catch_unwind::hd56632d711be2855
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/panic.rs:379
  24:     0x55e5dac2eade - std::rt::lang_start_internal::h90f188c8b72672f1
                               at /build/rust/src/rustc-1.47.0-src/library/std/src/rt.rs:51
  25:     0x55e5daaa6472 - main
  26:     0x7feac6eb7152 - __libc_start_main
  27:     0x55e5daa61a6e - _start
  28:                0x0 - <unknown>
```
I assume "auth sock variable" is related to ssh-agent but I don't use it at all.

**Comment by obreitwi** [comment]
>  I use two-factor auth

Ah, up until now I was under the impression you used a non-password-protected private key.
Could you elaborate a bit more? What form of 2FA-solution are you using? I would assume that they behave like an agent because if your private key was accessible without password, 2FA would be pointless… ;)

I would also be good if you could post an anonymized version of your config, because your error suggests `asfa` is trying to perform an agent-based auth but you wrote that you have set `use_agent` to `false`.

**Comment by ghost** [comment]
I am in fact using a non-password-protected private key in this situation. The server uses `libpam-google-authenticator` to implement 2FA and it works by adding a `Verification code:` interactive step, regardless of whether or not a password is used. Ideally this should work regardless of whether interactive password entry is used, or key-based authentication (regular ssh allows any combination).

~/.config/asfa/config.yaml
```
default_host: fsvr
prefix_length: 32
verify_via_hash: true
auth:
  interactive: false
  use_agent: false
```

~/.config/asfa/hosts/fsvr.yaml
```
hostname: x.x.x.x
folder: /var/www/fsvr
url: https://x.x.x.x
user: fsvr
group: www-data
```

**Comment by obreitwi** [comment]
Ah, thank you. :+1: 
Never used 2FA for ssh before, but have it set it up on my local machine now for testing purposes.

**Comment by obreitwi** [comment]
I just pushed a rework of the authentication procedure into the [`develop` branch](https://github.com/obreitwi/asfa/tree/develop). Locally, two factor authentication works for me.

Could you test if it works for you?

**Comment by ghost** [comment]
I still get ```thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { code: -39, msg: "no auth sock variable" }', src/ssh.rs:134:25``` regardless of the interactive setting, and `use_agent` is still false.

**Comment by obreitwi** [comment]
So it turns out that `asfa` always used agent auth if it wasn't disabled in each host-file specifically → just fixed it.

I can now use an unprotected private key file in conjunction with google authenticator and no agent.

Please note that you need to specify `private_key_file_password: ""` in the `auth` settings to explicitly tell `asfa` you are using an unprotected private key file and do not wish to be prompted for a passphrase.

**Comment by ghost** [comment]
If I specify both `private_key_file` and `private_key_file_password` (even though it is the default key for that user) that seems to work now at least. Thank you.

**Comment by obreitwi** [comment]
> that seems to work now

Very glad it does!

> even though it is the default key for that user

What do you mean by "default key for that user"?
Right now, the only "default" that `asfa` recognizes is its own `config.yaml` where you could specify an `auth` section with `private_key_file`/`private_key_file_password` that is used for every host.

If you tell me where you defined your "default key" in your setup I could maybe add a check for it.

**Comment by ghost** [comment]
By default I mean that when ssh is used normally, it always tries `~/.ssh/id_rsa` if it exists, and if that fails to authenticate, then it falls back to keyboard-interactive auth. I'm not sure if that path is hardcoded or what kind of system it actually uses to lookup user keys.

**Comment by obreitwi** [comment]
> it always tries `~/.ssh/id_rsa` if it exists

Ah, these are the [default keys for openSSH](https://manpages.debian.org/stretch/openssh-client/ssh_config.5.en.html#IdentityFile). According to documentation `libssh2` (that `asfa` [uses](https://docs.rs/ssh2/0.8.2/ssh2/struct.Session.html#method.userauth_pubkey_file)) only supports keys in the legacy PEM format.

But a quick trial-and-error showed that newly generated keys in openssh-format can indeed be read by `libssh2`. I might just add support to optionally use settings from openssh…

**Comment by ghost** [comment]
I think people would much prefer that as they might already have e.g. a `~/.ssh/config` that lists different hosts/alises, their hostnames, users, ports AND key files already and don't want to have to duplicate that for one program. I know other programs like `sshfs` read these same settings somehow, just not sure how easy it is with `libssh2` or if that's what is doing all the work.

**Comment by obreitwi** [comment]
`asfa` now has support to read basic settings such as private keys to use and hostnames from openSSH.

I plan on adding more if there is need (as long as there is support in `libssh2`).
